#[Info]
site_name: AsTr4 Docs   #网站名字
site_description: the notes record by AsTr4
site_author: AsTr4 #作者名
site_url: https://nekorana.github.io/  #网站地址
copyright: Copyright &copy; 2025 AsTr4 # 左下角的版权声明

# [Navigtion]
nav:
  - Home: index.md
  - Java: 
    - JavaSE:
      - Java的面向对象特性: java/se/oop.md
      - Java中的常用api: java/se/api.md
      - Java8新特性之lambda函数: java/se/lambda.md 
    - Java多线程: 
      - 介绍: java/mul-thread/index.md
      - 在Java中进行多线程编程: java/mul-thread/
  - leetcode:
    - 94.二叉树的中序遍历: leetcode/inorderTraversal.md
  - About: about.md

#[UI]
theme:
  name: material
  # custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

markdown_extensions:
  # - document-offsets-injection:
  #     # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true